--- /opt/amber11/src/pbsa/Makefile	2010-01-04 17:44:32.000000000 -0800
+++ Makefile	2010-01-04 16:20:00.000000000 -0800
@@ -37,10 +37,7 @@
 	cd ../lib && $(MAKE) nxtsec.o
 
 netlib: 
-	cd ../lapack && $(MAKE) $(LAPACK)
 	cd ../blas && $(MAKE) $(BLAS)
-	cd ../carpack && $(MAKE) install
-	cd ../f2c && $(MAKE) install
 
 c9x-complex:
 	@if test $(C9XCOMPLEX) != "skip"; then \
