--- Makefile	2010-02-09 15:36:06.000000000 -0800
+++ Makefile	2010-02-09 17:24:16.000000000 -0800
@@ -61,10 +61,7 @@
 	cd ../sff && $(MAKE) install
 
 netlib: 
-	cd ../lapack && $(MAKE) $(LAPACK)
 	cd ../blas && $(MAKE) $(BLAS)
-	cd ../carpack && $(MAKE) install
-	cd ../f2c && $(MAKE) install
 
 c9x-complex:
 	@if test $(C9XCOMPLEX) != "skip"; then \
