#define maxtime 22
#define TIME_TOTAL 1
#define TIME_READ 2
#define TIME_RUNMD 3
#define TIME_FORCE 4
#define TIME_BOND 5
#define TIME_NONBON 6
#define TIME_PBFORCE 7
#define TIME_PBLIST 8
#define TIME_PBSETUP 9
#define TIME_PBSAS 10
#define TIME_PBFDFRC 11
#define TIME_PBEPS 12
#define TIME_PBSOLV 13
#define TIME_PBITR 14
#define TIME_SINH 15
#define TIME_PBDBE 16
#define TIME_PBDIRECT 17
#define TIME_PBMP 18
#define TIME_NPFORCE 19
#define TIME_NPSAS 20
#define TIME_NPCAV 21
#define TIME_NPDIS 22
